# -*- coding:utf-8-unix -*-

[package]
name = "abc353"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
cli_test_dir = "0.1"
